services:
  mysql:
    image: mysql:8.0
    container_name: DM_project_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Lasv200427
      MYSQL_DATABASE: DM_project_db
      MYSQL_USER: Luis
      MYSQL_PASSWORD: Lasv200427
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: